# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name   = "Home"
  url    = "#about"
  weight = 10

[[main]]
  name   = "Research"
  url    = "research/"
  weight = 20
  
[[main]]
  name   = "Publications"
  url    = "publication/"
  weight = 30


[[main]]
  name   = "Course"
  url    = "course/"
  weight = 40
  

[[main]]
  name   = "Software"
  url    = "software/"
  weight = 50
  identifier = "software"        # Required for dropdown children
  
[[main]]
  name       = "XRO"
  url        = "software/xro"
  weight     = 51
  parent = "software"

[[main]]
  name       = "WNWR"
  url        = "software/wnwr"
  weight     = 52
  parent = "software"
  
[[main]]
  name       = "SDM"
  url        = "software/sdm"
  weight     = 53
  parent = "software"
  
  
[[main]]
  name       = "Climate"
  url        = "climate/"       # Makes it clickable
  weight     = 60
  identifier = "climate"        # Required for dropdown children

[[main]]
  name       = "Operational XRO Forecast"
  url        = "climate/xro"
  weight     = 61
  parent = "climate"
  
[[main]]
  name       = "Climate Atlas"
  url        = "climate/atlas"
  weight     = 62
  parent = "climate"

[[main]]
  name = "Posts"
  url = "post/"
  weight = 70

[[main]]
  name = "Links"
  url = "link/"
  weight = 90

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.

# [[main]]
#   name = "CV"
#   url = "cv_sen.pdf"
#   weight = 110


#[[main]]
#  parent = "climate"
#  name = "Atlas"
#  url = "climate/clim_anom/"
#  weight = 60

#[[main]]
#  parent = "climate"
#  name = "Forecasts"
#  url = "climate/forecast/"
#  weight = 60